### ISSUE TITLE
error on compiling nehe02

### ISSUE THREAD

**Issue by Cyan4973** [dreamcastdevs/dreamcast_tutorial#2]
`make` compilation outcome in dreamcast_tutorial/02_drawing_using_GLdc/nehe02/
 : 

```
kos-cc  -c main.c -o main.o
/opt/toolchains/dc/kos/utils/genromfs/genromfs -f romdisk.img -d romdisk -v
0    rom 5e6d3df4         [0xffffffff, 0xffffffff] 37777777777, sz     0, at 0x0     
1    .                    [0x803     , 0x865e76  ] 0040755, sz     0, at 0x20    
1    ..                   [0x803     , 0x865e6e  ] 0040755, sz     0, at 0x40     [link to 0x20    ]
1    PLACEHOLDER          [0x803     , 0x865e77  ] 0100644, sz     0, at 0x60    
/opt/toolchains/dc/kos/utils/bin2o/bin2o romdisk.img romdisk romdisk.o
/opt/toolchains/dc/sh-elf/bin/sh-elf-gcc -O2 -fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections  -I/opt/toolchains/dc/kos/include -I/opt/toolchains/dc/kos/kernel/arch/dreamcast/include -I/opt/toolchains/dc/kos/addons/include -I/opt/toolchains/dc/kos/../kos-ports/include -D_arch_dreamcast -D_arch_sub_pristine -Wall -g -fno-builtin  -ml -m4-single-only -Wl,-Ttext=0x8c010000 -Wl,--gc-sections -T/opt/toolchains/dc/kos/utils/ldscripts/shlelf.xc -nodefaultlibs -L/opt/toolchains/dc/kos/lib/dreamcast -L/opt/toolchains/dc/kos/addons/lib/dreamcast -L/opt/toolchains/dc/kos/../kos-ports/lib -o main.elf  \
        main.o romdisk.o  -Wl,--start-group -lkallisti -lc -lgcc -Wl,--end-group -lkosutils -lGLdc -lm
/opt/toolchains/dc/sh-elf/lib/gcc/sh-elf/4.7.3/../../../../sh-elf/bin/ld: /opt/toolchains/dc/kos/addons/lib/dreamcast/libGLdc.a(texture.o): in function `_initTexturePalette':
/opt/toolchains/dc/kos/addons/GLdc/GL/texture.c:33: undefined reference to `_memset4'
```

The issue seems located on `GLdc` side:
https://gitlab.com/simulant/GLdc/-/blob/master/GL/texture.c#L33 . 
Maybe it would be safer to lock down a version or tag, to avoid inheriting bugs or changes in later versions ?

Note : the issue also impacts `03_controller_interaction/simple_control`, but not the neighboring project `02_drawing_using_GLdc/png-texture`.

**Comment by Cyan4973** [comment]
Fixed by modifying `GLdc` source code directly.

**Comment by Protofall** [comment]
For the record what version of GCC were you using? I've had issues compiling it on GCC 7.X, but generally 4.7.3 works fine

**Comment by Cyan4973** [comment]
Since I'm using KOS, the compiler is `kos-cc`, which is based on 4.7.3.

I think the issue is unrelated to `gcc`.
Rather, it's the `GLdc` project which introduced a bug in its latest commit, which was easily fixed by changing back an invocation of `memset4()` (which doesn't exist) into `memset()`.

That's why I was wondering if the tutorial could link to a specific version of `GLdc`, rather than "latest" one, which could introduce any kind of change or bug in the future, breaking the tutorial.

**Comment by Protofall** [comment]
I've definitely heard of memset4. It must not be included correctly then. I'm not 100% sure where it comes from though

**Comment by Protofall** [comment]
memset4 is part of the dan porter library. People have told me this error shouldn't be occurring.

Also note memset is much slower than memset4 (Up to 4 times slower)

**Comment by mrneo240** [comment]
It's a part of kos and is linked if you use libkallisti which GLdc depends on, more info needed.

[http://cadcdev.sourceforge.net/docs/kos-current/string_8h.html](http://cadcdev.sourceforge.net/docs/kos-current/string_8h.html) 

And

[https://github.com/KallistiOS/KallistiOS/blob/master/kernel/libc/koslib/memset4.c](https://github.com/KallistiOS/KallistiOS/blob/master/kernel/libc/koslib/memset4.c)
